import = [
"~/.alacritty.local.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7f7f7f"
blue = "#5c5cff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#3465a4"
cyan = "#00cdcd"
green = "#00cd00"
magenta = "#cd00cd"
red = "#cd0000"
white = "#e5e5e5"
yellow = "#cdcd00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[env]
TERM = "xterm-256color"

[font.bold]
style = "SemiBold"

# [font]
# size = 10.0
# On MacBook
# size = 16.0

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullScreen"

# [[keyboard.bindings]]
# chars = "\u001Bf"
# key = "F"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001Bb"
# key = "B"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "#"
# key = "Key3"
# mods = "Alt"

[window]
option_as_alt = "Both"

