AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 20
