#! /usr/bin/env sh

echo "Max brightness value:"
cat /sys/class/backlight/gmux_backlight/max_brightness

echo "Previous brightness value:"
cat /sys/class/backlight/gmux_backlight/brightness

echo "New brightness value:"
sudo echo $1 | sudo tee /sys/class/backlight/gmux_backlight/brightness

